version: '3.7'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=examplepassword
